### ISSUE TITLE
Getting token using API

### ISSUE THREAD

**Issue by MathMan05** [towerofnix/scratch-api-unofficial-docs#60]
I have no idea how to do this and the website doesn't show me how, can someone please add that it's a wonderful website and has all I need but I don't know how to get a token.

**Comment by towerofnix** [comment]
We've been (very much idly) meaning to port this over to the wiki for a while, but for the moment this guide we wrote a year or so ago should show you all the details: https://gist.github.com/towerofnix/cd5c0771446dc0ba81355fccc70ed1ea

**Comment by MathMan05** [comment]
I still don't really understand, is this what it needs or is there an error?
URL: https://scratch.mit.edu/login/
Post:"{mathman05,<password>,useMessages: true}"
headers: [["a", "XMLHttpRequest"], ["scratchcsrftoken=a;scratchlanguage=en;", "https://scratch.mit.edu"]]

**Comment by towerofnix** [comment]
I don't really know what the code you're writing looks like, so it's hard for me to say for certain. Obviously with password/etc censored, could you show how you're sending that request?

--That said, it turns out my document is missing some information, I'm really sorry I didn't notice that before >_<

The request you send should look like this:
* method: `POST`
* url: `https://scratch.mit.edu/login/`
* body: `{"username":"...","password":"..."}
* `Referer` header: `https://scratch.mit.edu`
* `X-CSRFToken` header: `a`
* `Cookie` header: `scratchcsrftoken=a;`

A successful response will have the header `set-cookie` set, which will contain a string like `scratchsessionsid=whatever`. You can parse that and use that as a cookie in fetching the API token and user session data (which is accurately described [here](https://gist.github.com/towerofnix/cd5c0771446dc0ba81355fccc70ed1ea#api-token-and-session-data)).

You can use this as reference code: https://github.com/trumank/scratch-api/blob/3286d9e19ab499106599d5fece67858cd4a3f004/scratchapi.js#L93-L98

**Comment by MathMan05** [comment]
can I get an example of what the body needs to be? is it like {Mathman05,<password>}

**Comment by towerofnix** [comment]
Yeah, the body will be a string. But it is going to be written in JSON format, i.e. similarly to a JavaScript object. That's why it's `{"username":"...","password":"..."}`. So if you're signing in as account `foo` with the password `P4SS123` then the body of the request would be `{"username":"foo","password":"P4SS123"}`. You would also want to set all the headers like I described above.

**Comment by MathMan05** [comment]
when I said can it be a string I meant if the whole {"username":"foo","password":"P4SS123"} was a string

**Comment by MathMan05** [comment]
![image](https://user-images.githubusercontent.com/73901602/98066237-0a8f1980-1e1c-11eb-9baa-a82f15b6215a.png)
this is what I've made and it still doesn't work do you know why?

**Comment by MathMan05** [comment]
I think the header is fine, as if I change it, it stops working

**Comment by MathMan05** [comment]
I figured it out! thank you so much for your help!

**Comment by towerofnix** [comment]
Glad to have helped! Also, it's super neat to see you using a block language to interact with Scratch :)

(For future ref: Pretty sure the issue here is that the "username" and "mathman05" blocks, etc, were missing the *inner* quotation marks necessary -- i.e, the result string would be like `{username:mathman05,...}` instead of `{"username":"mathman05"}`. Everything else looks right here!)

**Comment by MathMan05** [comment]
no, the quotation marks were the thing that was missing I thought they weren't needed, but they were, thank you for the help here is the scratch discussion about it: https://scratch.mit.edu/discuss/topic/453748/?page=1#post-4565890

**Comment by MathMan05** [comment]
thnk you so much for your help and I hope the 12 steps gives others some help on their way to getting the token! :D
