### ISSUE TITLE
Explain project JSON from projects.scratch.mit.edu...

### ISSUE THREAD

**Issue by IoIxD** [towerofnix/scratch-api-unofficial-docs#72]
I'm currently working on a Rust library for getting project code to help with a much larger project, and I've decided to devote some extra time to make this Rust-idomatic in place of the many unnamed arrays and such ([example](https://github.com/IoIxD/YASE/issues/1)).

Doing this has been a challenge and I may end up documenting what I find myself, but it would also be nice if somebody more familiar with the API

**Comment by IoIxD** [comment]
I'm specifically working on discrete block types based on the inputs/fields array and if nothing else I'd like some explaination on what shadow and top_level (are those hat blocks?) are.
![image](https://user-images.githubusercontent.com/30945097/199805104-f624b57a-a4d2-4c44-9df9-c97c5fece1e2.png)

**Comment by towerofnix** [comment]
While I haven't worked on the repo for a while anyhow (but still welcome PRs), `project.json` files are unfortunately definitely out of scope - this project is for documenting the behavior and usage for the Scratch API, particularly as it relates to interacting with the Scratch community website. So, documenting API endpoints for sharing projects and updating project files (including `project.json`) are in scope, but details on the actual `project.json` format are out of scope, because those are only consumed by the Scratch 3.0 editor/player (and alternatives) and don't really have anything to do with the community site itself.

You use the same endpoints to work with broken or nonsensical project data as you do with normal ones, the job of this particular wiki isn't to detail how to generate or process that data—it's for showing how to put that data onto the site itself.

To be clear, I'd seriously *love* to make a complete documentation of the Scratch 3.0 project.json format. I've literally spent hours idly fantasizing over a literal book that covers the entire architecture of the Scratch editor and player, with fully detailed sections on project serialization and deserialization. It's just, that's a completely separate project from website API docs (and kind of a big undertaking lol), so I hope it's clear why I'm choosing not to include `project.json` documentation here!

To give a hand with your own project, you can find some essential info on the `project.json` format on the Scratch Wiki, see [Scratch File Format](https://en.scratch-wiki.info/wiki/Scratch_File_Format). Reference implementations for the sb3 format, which include complete information and specifics on the actual processing Scratch does, can be found [in LLK's own scratch-vm project](https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb3.js) (underlying 3.0 itself) and [the sb-edit implementation for Leopard](https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb3.js) (unofficial/community project, I basically wrote the toSb3.ts serialization file form scratch and it has a lot of tech details on how block serialization works. There are probably other sb3 de/serialization projects out there too, these are just the two I'm most familiar with.

I hope some of this helps! You're also welcome to share your own findings on your own wiki or site/blog (and link it here for those interested), it's just the subject isn't a particularly close fit for this wiki.
